config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'signup', to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :photos, only: [:new, :show]
  resources :favorites, only: [:create, :destroy]
  resources :categories
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }
    
    has_many :photos
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :photo, class_name: "Photo"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    belongs_to :category
    
    has_many :favorites, class_name: "Favorite", foreign_key: "photo_id", dependent: :destroy
    has_many :favoriting_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :favorites, class_name: "Favorite", foreign_key: "user_id", dependent: :destroy
    has_many :favorite_photos, through: :favorites, source: :photo
    
    # 写真をお気に入りする
    def favorite(photo)
        favorites.find_or_create_by(photo_id: photo.id)
    end
    
    # お気に入りを解除する
    def unfavorite(photo)
        favorites.find_by(photo_id: photo.id).destroy
    end
    
    # ある写真をお気に入りしているかどうか？
    def favoriting?(photo)
        favorite_photos.include?(photo)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "カテゴリを追加しました！"
            redirect_to new_category_path
        else
          render new_category_path
        end
    end
    
    def show
        FlickRaw.api_key       = Rails.application.secrets.flickr_api_key
        FlickRaw.shared_secret = Rails.application.secrets.flickr_shared_secret
        word = @category.name
        @photos = flickr.photos.search(text: word, license: "1,2,3,4,5,6", sort: "relevance", per_page: 30)
    end
    
    private

    def category_params
        params.require(:category).permit(:name)
    end
    
    def set_category
        @category = Category.find(params[:id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :logged_in_user
    
    def create
        if params[:flickr_id]
            @photo = Photo.find_or_initialize_by(flickr_id: params[:flickr_id])
        else
            @photo = Photo.find(params[:photo_id])
        end
        
        # photosテーブルに存在しない場合はFlickrのデータを登録する。
        if @photo.new_record?
            
            @photo_info = flickr.photos.getInfo(:photo_id => params[:flickr_id])
            @photo.flickr_id = @photo_info.id
            @photo.title = @photo_info.title
            @photo.link_url = FlickRaw.url_photopage(@photo_info)
            @photo.thumbnail_url = FlickRaw.url_z(@photo_info)
            @photo.original_url = FlickRaw.url_o(@photo_info)
            @photo.save!
        end
        
        current_user.favorite(@photo)
    end
    
    def destroy
        @photo = current_user.favorites.find(params[:id]).photo
        current_user.unfavorite(@photo)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
    def new
        if params[:q]
            FlickRaw.api_key       = Rails.application.secrets.flickr_api_key
            FlickRaw.shared_secret = Rails.application.secrets.flickr_shared_secret
            word = params[:q]
            @photos = flickr.photos.search(text: word, license: "1,2,3,4,5,6", sort: "relevance", per_page: 30)
        end
    end
    
    def show
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "ログインできました！#{@user.name}さん、こんにちは！"
      redirect_to @user
    else
      flash[:danger] = 'メールアドレスかパスワードがまちがっています。'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録ができました！マイアルバムをつくりましょう！"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @photos = @user.favorite_photos.group('photos.id')
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新できました！"
      redirect_to user_path
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @photos = Photo.all.order("updated_at DESC").limit(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/new.html.erb
<div class="center">
    <h1>カテゴリ作成</h1>
    <%= form_for(@category) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit "カテゴリ作成", class: "btn btn-large btn-danger" %>
    <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render 'photos/flickr_search' , photos: @photos %>

app/views/favorites/create.js.erb
$(".favorite-<%= @photo.flickr_id %>").replaceWith("<%= escape_javascript(render('photos/unfavorite' , photo: @photo)) %>");
$('.btn-favorite').removeAttr('disabled');

app/views/favorites/destroy.js.erb
$(".favorite-<%= @photo.flickr_id %>").replaceWith("<%= escape_javascript(render('photos/favorite' , photo: @photo)) %>");
$('.btn-favorite').removeAttr('disabled');

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-inner">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/">ぼくのでんしゃアルバム</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <% unless logged_in? %>
                      <li><%= link_to "新規登録", signup_path %></li>
                      <li><%= link_to "ログイン", login_path %></li>
                    <% else %>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            しんかんせん
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li>
                              <%= link_to "はやぶさ", "/categories/1" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "スーパーこまち", "/categories/2" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "かがやき", "/categories/3" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "E4系", "/categories/4" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "N700系", "/categories/5" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "700系", "/categories/6" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "500系", "/categories/7" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "800系", "/categories/8" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "ドクターイエロー", "/categories/9" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "イーストアイ", "/categories/10" %>
                            </li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            とっきゅう
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li>
                              <%= link_to "スカイライナー", "/categories/11" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "成田エクスプレス", "/categories/12" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "スーパービュー", "/categories/13" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "りょうもう", "/categories/14" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "ラピート", "/categories/15" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "はくたか", "/categories/16" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "カシオペア", "/categories/17" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "スーパーひたち", "/categories/18" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "スペーシア", "/categories/19" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "しまんと", "/categories/20" %>
                            </li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            つうきんでんしゃ
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li>
                              <%= link_to "山手線", "/categories/21" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "湘南新宿ライン", "/categories/22" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "東海道本線", "/categories/23" %>
                            </li>
                            <li>
                              <%= link_to "京急電鉄", "/categories/24" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "東京急行電鉄", "/categories/25" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "西武鉄道", "/categories/26" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "阪急電鉄", "/categories/27" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "京阪電鉄", "/categories/28" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "名古屋鉄道", "/categories/29" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "マリンライナー", "/categories/30" %>
                            </li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            いろんなでんしゃ
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li>
                              <%= link_to "蒸気機関車", "/categories/31" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "モノレール", "/categories/32" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "貨物車", "/categories/33" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "路面電車", "/categories/34" %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                              <%= link_to "超電導リニア", "/categories/35" %>
                            </li>
                          </ul>
                      </li> 
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          <span class="gravatar">
                            <%= gravatar_for current_user , size: 20 %>
                          </span>
                          <%= current_user.name %>
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li>
                            <%= link_to "マイアルバム" , current_user  %>
                          </li>
                          <li role="separator" class="divider"></li>
                          <li>
                            <%= link_to "ログアウト", logout_path, method: "delete" %>
                          </li>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TrainAlbum</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <% #TODO メタタグやタイトル、ディスクリプションの設定 %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      
      <!-- フラッシュメッセージの表示 -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/photos/_action.html.erb
<div class="action center">
    <% if current_user.favoriting? photo %>
        <%= render 'photos/unfavorite' , photo: photo %>
    <% else %>
        <%= render 'photos/favorite' , photo: photo %>
    <% end %>
</div>

app/views/photos/_favorite.html.erb
<%= link_to "おきにいり" , favorites_path(photo_id: photo.id) ,
                    :class => "btn btn-favorite favorite-#{photo.id} btn-warning",
                    :remote => true,
                    :method => :post %>

app/views/photos/_flickr_search.html.erb
<% @photos.each do |photo| %>
    <div class="center">
        <img src=<%= "http://farm#{photo.farm}.static.flickr.com/#{photo.server}/#{photo.id}_#{photo.secret}_z.jpg" %>>
        <div class="action">
            <% if current_user.favoriting? photo %>
                <%= link_to "おきにいりをやめる" , favorite_path( current_user.favorites.find_by(:flickr_id => photo.id) , flickr_id: photo.id ) ,
                        :class => "btn btn-favorite favorite-#{photo.id} btn-default",
                        :remote => true,
                        :method => :delete %>
            <% else %>
                <%= link_to "おきにいり" , favorites_path(flickr_id: photo.id) ,
                        :class => "btn btn-favorite favorite-#{photo.id} btn-warning",
                        :remote => true,
                        :method => :post %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/photos/_list.html.erb
<% photos.each do |photo| %>
    <div>
        <img src=<%= "#{photo.thumbnail_url}" %>>
        <div class="action">
            <%= render 'photos/action', photo: photo if logged_in? %>
        </div>
    </div>
<% end %>

app/views/photos/_unfavorite.html.erb
<%= link_to "おきにいりをやめる" , favorite_path( current_user.favorites.find_by(:photo_id => photo.id) , photo_id: photo.id ) ,
                    :class => "btn btn-favorite favorite-#{photo.id} btn-default",
                    :remote => true,
                    :method => :delete %>

app/views/photos/new.html.erb
<div class="search center">
  <%= form_tag new_photo_path , method: :get do %>
    <%= text_field_tag :q , params[:q], placeholder: "キーワードを入れましょう", required: true %>
    <%= submit_tag "写真をさがす", name: nil , class: "btn btn-success", data: { disable_with: "検索中..."} %>
  <% end %>
</div>
<div class="search-result center">
  <% if @photos.present? %>
    <%= render 'flickr_search' , photos: @photos %>
  <% elsif params[:q].present? %>
    <div class="alert alert-danger">
      <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
      検索したキーワードの写真はありませんでした。
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation center">
        <div class="alert alert-danger">
            <%= pluralize(object.errors.count, "error") %> つエラーがあります。
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="box center">
    <h2 class="box-title">プロフィール変更</h2>
    <div class="box-inner form-hotizontal">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group">
                <label class="col-sm-2 control-label"><%= f.label :name, "なまえ" %></label>
                <div class="col-sm-10"><%= f.text_field :name, class: "form-control" %></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><%= f.label :email, "メールアドレス" %></label>
                <div class="col-sm-10"><%= f.email_field :email, class: "form-control" %></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><%= f.label :password, "パスワード" %></label>
                <div class="col-sm-10"><%= f.password_field :password, class: "form-control" %></div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label"><%= f.label :password_confirmation, "パスワード（確認）" %></label>
                <div class="col-sm-10"><%= f.password_field :password_confirmation, class: "form-control" %></div>
            </div>
            <div class="submit-group col-sm-offset-2 col-sm-10">
                <%= f.submit "更新する", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="box center">
    <h2 class="box-title">新規登録</h2>
    <div class="box-inner">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group">
                <%= f.text_field :name, class: "form-control", placeholder: "なまえ" %>
            </div>
            <div class="form-group">
                <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
            </div>
            <div class="form-group">
                <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
            </div>
            <div class="form-group">
                <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）" %>
            </div>
            <div class="submit-group">
                <%= f.submit "登録する", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="center">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <div>
    おきにいり <strong><%= @user.favorite_photos.count %></strong>まい
  </div>
  <div>
    <% if current_user == @user %>
      <%= link_to "プロフィール変更" , edit_user_path, class: "btn btn-success" if logged_in? %>
    <% end %>
  </div>
  <%= render 'photos/list', photos: @photos %>
</div>

app/views/welcome/index.html.erb
<div class="center">
    <h1>ぼくのでんしゃアルバム</h1>
    <p>
        <%= link_to "写真をさがす", new_photo_path, class: "btn btn-primary" %>
    </p>
    <%= render 'photos/list', photos: @photos %>
</div>